In [41]:
# Troubleshooting.  So my quad doesn't want to learn.
# Let's try the gym models
import sys
import gym
import numpy as np
import matplotlib.pyplot as plt
from task_mountain import Task
from agents.mountain_car import DDPG

%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [42]:
# Setup
task = Task()
num_episodes = 50
agent = DDPG(task)

for i_episode in range(1, num_episodes + 1):
    state = agent.reset_episode()       # start a new episode
    
    while True:
        action = agent.act(state)
        next_state, reward, done = task.step(action)
        agent.step(action, reward, next_state, done)
        state = next_state
        
        if done:
            print('\rEpisode = ', i_episode, end="")
            break
    sys.stdout.flush()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Episode =  50

In [48]:
done = False
state = agent.reset_episode()
count = 0

while True:
    count += 1
    task.env.render()
    state = np.reshape(state, [-1, 6])
    action = agent.actor_local.model.predict(state)[0]
    state, reward, done = task.step(action)
    print('\rCount = ', count, ', Reward = ', reward, end="")
    state = np.concatenate([state] * 3)
    if done:
        break 

Count =  333 , Reward =  -0.0999997615815630188 , Reward =  -0.1 223 , Reward =  -0.1

In [27]:
r = env.reset()

In [28]:
r

array([-0.46285219,  0.        ])

In [35]:
state, reward, done, info = env.step([0.0])

In [39]:
info

{}

In [33]:
for _ in range(10):
    print(env.step([-1.0]))

(array([-0.49645801, -0.00602549]), -0.1, False, {})
(array([-0.50418683, -0.00772882]), -0.1, False, {})
(array([-0.51356116, -0.00937433]), -0.1, False, {})
(array([-0.52451077, -0.0109496 ]), -0.1, False, {})
(array([-0.53695353, -0.01244276]), -0.1, False, {})
(array([-0.55079616, -0.01384263]), -0.1, False, {})
(array([-0.56593503, -0.01513887]), -0.1, False, {})
(array([-0.58225724, -0.01632221]), -0.1, False, {})
(array([-0.59964177, -0.01738453]), -0.1, False, {})
(array([-0.61796092, -0.01831915]), -0.1, False, {})
